import { NextPage } from 'next'
import Head from 'next/head'
import Layout from '../components/Layout/Layout'
import {
  Box,
  Text,
  VStack,
  Button,
  Input,
  InputGroup,
  InputLeftElement,
  Flex,
  Image,
  Icon,
  HStack
} from '@chakra-ui/react'
import { BsSearch } from 'react-icons/bs'
import Categories from '@components/HomePage/Categories'

const Home: NextPage = () => {
  return (
    <Layout>
      <Head>
        <title>724Desk</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Box
        bgImage={'/HomePageBg.png'}
        w={'full'}
        h={'746px'}
        bgPos={'center'}
        bgSize={'cover'}
      >
        <Flex
          flexDirection={'column'}
          px={125}
          justifyContent={'center'}
          h={'full'}
          gap={10}
        >
          <Text fontSize={'54px'}>
            Problemlerinize <br /> Anında{' '}
            <span style={{ color: '#F27C00' }}>
              Çözüm <br /> Bulun!
            </span>
          </Text>
          <Button bg={'#F27C00'} color={'white'} w={'242px'} gap={4}>
            <Image
              src={'/hpButtonIcon.png'}
              alt={'icon'}
              w={'21.5px'}
              h={'21.5px'}
            />
            Destek Talebi Oluştur
          </Button>
          <InputGroup
            size={'lg'}
            w={'389px'}
            rounded={5}
            boxShadow={'xl'}
            alignItems={'center'}
          >
            <InputLeftElement h={'full'}>
              <Icon as={BsSearch} />
            </InputLeftElement>
            <Input placeholder='Problemlerinizi yazın ve arayın'></Input>
          </InputGroup>
          <HStack>
            {Item.map(item => (
              <Button key={item.key} name={item.name} rounded={99} border={"1px solid"} borderColor={"rgba(0,0,0,0.1)"} color={"rgba(0, 0, 0, 0.5)"} fontSize={"13px"}>
                {item.name}
              </Button>
            ))}
          </HStack>
        </Flex>
      </Box>
      <Categories/>
    </Layout>
  )
}

export default Home

interface buttonProps {
  name: string
  key: string
}

const Item: Array<buttonProps> = [
  { name: 'Kripto', key: 'crypto' },
  { name: 'Bitcoin', key: 'btc' },
  { name: 'Şarj Kablosu', key: 'şarj' },
  { name: 'Staking', key: 'staking' }
]
