import { NextPage } from 'next'
import Head from 'next/head'
import Layout from '../components/Layout/Layout'


const Home: NextPage = () => {
  return (
    <Layout>
      <Head>
        <title>724Desk</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
    </Layout>
  )
}

export default Home
